# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
zh:
  languageCode: zh
  # contentDir: content/zh
  title: 云原生资料库
  params:
    description: 一站式云原生资料库
    code_copy: true
    anchored: true # add anchor on each head title in the blog article content
    code_copy_button: true
    back_to_top_button: true
    locale:
      date_format: '2006-01-02'
      time_format: '下午 3:04'

# en:
#   languageCode: en-us
#   contentDir: content/en
